services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile.humble
    command: /bin/sh -c "while sleep 1000; do :; done" 
    environment:
      - DISPLAY
      - XAUTHORITY
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/home/vscode/workspace:cached
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  isaac-sim:
    #image: nvcr.io/nvidia/isaac-sim:2022.2.1
    build:
      context: .
      dockerfile: Dockerfile.isaac
    entrypoint: bash  -c "sleep 1 && unset LD_LIBRARY_PATH && sleep 1 &&./runapp.sh"
    environment:
      - ACCEPT_EULA=Y
      - DISPLAY
      - FASTRTPS_DEFAULT_PROFILES_FILE=/isaac-sim/ros2_workspace/fastdds.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/isaac-sim/.Xauthority
      - ..:/tmp/project
      - ~/docker/isaac-sim/cache/Kit:/isaac-sim/kit/cache/Kit:rw
      - ~/docker/isaac-sim/.cache:/home/isaac-sim/.cache:rw
      - ~/docker/isaac-sim/.nv:/home/isaac-sim/.nv:rw
      - ~/docker/isaac-sim/.nvidia-omniverse:/home/isaac-sim/.nvidia-omniverse:rw
      - ~/docker/isaac-sim/.local:/home/isaac-sim/.local:rw
      - ~/docker/isaac-sim/documents:/home/isaac-sim/Documents:rw
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]